name: "Иван Бущик"
url: https://ivabus.dev
description: "ivabus"
lang: ru-RU
timezone: Europe/Moscow


permalink: "/:year/:month/:day/:title/"
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'LICENSE']

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap